### ISSUE TITLE
support vtt also for dualsubs-creat.lua

### ISSUE THREAD

**Issue by mrfragger** [VimWei/mpv-config#1]
```
 51     local major, minor = time:match("(%d%d:%d%d:%d%d),(%d%d%d)")
51     local major, minor = time:match("(%d%d:%d%d:%d%d)[,%.](%d%d%d)")
```

```
102   if file_extension == "srt" then
103        for start_time, end_time, text in string.gmatch(data, "(%d%d:%d%d:%d%d,%d%d%d) %-%-> (%d%d:%d%d:%d%d,%d%d%d)\n(.-)\n\n") do
```

```
102   if file_extension == "srt" or "vtt" then
103        for start_time, end_time, text in string.gmatch(data, "(%d%d:%d%d:%d%d[,%.]%d%d%d) %-%-> (%d%d:%d%d:%d%d[,%.]%d%d%d)\n(.-)\n\n") do
```

tested it and it works with srt and vtt although have to put in the actual directory to get it to work as working-directory isn't returning anything. I'm on a Mac. 

258    local subtitles_filename = mp.get_property("working-directory") .."Users/mrfragger/Desktop/mpvdata/editing/" .. mp.get_property("filename/no-ext") .. "_bilingual.ass"

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/d3d00ba4-4123-434e-bd71-6dfa17dfe050">

**Comment by VimWei** [comment]
https://github.com/mpv-player/mpv/issues/7573

**Comment by VimWei** [comment]
You can first convert VTT to SRT using SubtitleEdit or similar tools.
