### ISSUE TITLE
chapter-convert only first chapter written

### ISSUE THREAD

**Issue by mrfragger** [VimWei/mpv-config#2]
youtube to mpv writes

video.chapter
0:16.320 ABC

mpv to youtube writes to video.mp4.chapter
;FFMETADATA1
[CHAPTER]
START=16320000000
END=477448707482
title=Chapter 1 ABC

however using chapters_for_mpv
;FFMETADATA1
;file=/Users/username/data/mpv/editing/video.mp4
[CHAPTER]
START=16320000000
END=82560000000
title=Chapter 1 ABC
[CHAPTER]
START=82560000000
END=133720000000
title=Chapter 2 DEF
[CHAPTER]
START=133720000000
END=175520000000
title=Chapter 3 GHI
[CHAPTER]
START=175520000000
END=477448707482.99
title=JKL

**Comment by VimWei** [comment]
> youtube to mpv writes
> 
> video.chapter 
>0:16.320 ABC
> 
> mpv to youtube writes to video.mp4.chapter 
> ;FFMETADATA1 
> [CHAPTER] 
> START=16320000000 
> END=477448707482 
> title=Chapter 1 ABC
> 

The input matches the output, which is exactly the effect that chapter-convert hopes to achieve. I don't understand what your question is.

Your input only includes ABC, without DEF, GHI, and JKL, so there will naturally be no corresponding output.

**Comment by mrfragger** [comment]
no the input was the same for all 3 of them.  I'm saying it's only writing the first chapter when it should write all four chapters which only chapters_for_mpv is doing.

**Comment by VimWei** [comment]
You can use chapter-convert's mpv-to-youtube to convert .ffmetadata to .chapter, and compare the result .chapter file with  your .chapter file to find the problem.
